steps:

- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - '-m'
    
    - '-d'
    - '-r'
    - 'dags'
    - 'tron'
    - 'gs://${_GCS_BUCKET_1}.destination/'
    #Logging
options:
  logging: CLOUD_LOGGING_ONLY
#completed
